### PR TITLE
fix style list not being merged into module definition

### PR DESCRIPTION
**Pull request by oetterer**
when using extension bootstrap outside skin chameleon, style and js
module definition did not merge correctly.

### CODE REVIEW

**Comment by oetterer** [comment]
closes #11

**Comment by JeroenDeDauw** [comment]
@oetterer can you add a short note what this does from a user perspective to https://github.com/ProfessionalWiki/Bootstrap/blob/master/docs/release-notes.md?

**Comment by oetterer** [comment]
@JeroenDeDauw like this?

**Comment by JeroenDeDauw** [comment]
That works!

**Pull request merged**
